const quiz = [
    {
        q:'Explain functional view in an organization?',
        options: ['Divided subcompanies','Divided benefits','Merging Companies','Bankruptcy'],
        answer: 0,
        topic: "Exam 3"
    },
    {
        q:'What word describes the main benefit of functional view businesses?',
        options: ['Smaller/easier','Larger/harder','Medium/quicker','Greater/smaller'],
        answer: 0,
        topic: "Exam 3"
    },
    {
        q:'What do you lose the most in a functional view business?.',
        options: ['Manufacturing','Production','Efficiency','Advertising'],
        answer: 2,
        topic: "Exam 3"
    },
    {
        q:'What is a process approach in a company?',
        options: ['Single goal','Multiple projects.', 'Lots of departments', 'Sole proprietor'],
        answer: 0,
        topic: "Exam 3"
    },
    {
        q:'What is a major benefit of the process approach to business?',
        options: ['Single Goal','Working alone','Overtime','Happiness'],
        answer: 0,
        topic: 'Exam 3'
    },
    {
        q:'What is a workflow?',
        options: ['Bathroom break','Steps to completion', 'Indie Band', 'Business jargon'],
        answer: 1,
        topic: 'Exam 3'
    },
    {
        q:'What is 35% of the problem with new hires?',
        options: ['Manager buy-in.','Employee buy-in.','Customers.','Advertising.'],
        answer: 0,
        topic: 'Exam 3'
    },
    {
        q:'What does a workflow diagram represent?',
        options: ['Life','Chaos', 'Visual order', 'Benefits'],
        answer: 2,
        topic: 'Exam 3'
    },
    {
        q:'Why use a workflow diagram?',
        options: ['Universal understanding','Insurance','Executive Jargon','Little Understanding'],
        answer: 0,
        topic: 'Exam 3'
    },
    {
        q:'What is an oval in a diagram?',
        options: ['Input','Output', 'Process', 'Beginning and end'],
        answer: 3,
        topic:'Exam 3',
    },
    {
        q:'What is a rectangle in a workflow diagram?',
        options: ['Output','Start/stop', 'Process', 'Single task.'],
        answer: 3,
        topic:'Exam 3'
    },
    {
        q:'What is a diamond in a workflow diagram?',
        options: ['Input','Process','Decision','Single task.'],
        answer: 2,
        topic: 'Exam 3'
    },
    {
        q:'What are parallelograms in a workflow activity?',
        options: ['Input/output','Process','Decision','Output'],
        answer: 0,
        topic: 'Exam 3'
    },
    {
        q:'What are bullet shaped symbols in a workflow diagram?',
        options: ['Life','Known delays','Decisions','Input'],
        answer: 1,
        topic: 'Exam 3'
    },
    {
        q:'What begins a workflow diagram?',
        options: ['Shift work','Customers', 'Bosses', 'Information'],
        answer: 3,
        topic: 'Exam 3'
    },
    {
        q:'Who begins a workflow diagram?',
        options: ['Anyone','Customers','Gym goers','Parrots'],
        answer: 0,
        topic: 'Exam 3'
    },
    {
        q:'What are the three basic components of a workflow?',
        options: ['Beneath. Over. Middle.','In. Out. On.', 'Out. In. Over.', 'Input. Transformation. Output.'],
        answer: 3,
        topic: 'Exam 3'
    },
    {
        q:'What is input in a workflow diagram?',
        options: ['Anything.','Beer.', 'Emails.', 'Reports.'],
        answer: 0,
        topic: 'Exam 3'
    },
    {
        q:'What is transformation in a workflow diagram?',
        options: ['Reports','Process', 'Raw Data', 'Directed input.'],
        answer: 3,
        topic: 'Exam 3'
    },
    {
        q:'What is output in a workflow diagram?',
        options: ['Production','Product', 'Raw materials', 'Reports'],
        answer: 1,
        topic: 'Exam 3'
    },
    {
        q:'What is the goal of efficiency in a workflow?',
        options: ['Customers.','Get sales more breaks.', 'Let management get bonuses.','Grow employees more responsible.'],
        answer: 3,
        topic: 'Exam 3'
    },
    {
        q:'How does information flow through an organization?',
        options: ['Vertical and Horizontal','Backwards','Forwards','Reverse'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'How does consistency work in a workflow diagram?',
        options: ['Creates less consistency.','Exponential growth.','Creates more consistency.','Vacations for sales.'],
        answer: 2,
        topic:'Exam 3',
    },
    {
        q:'How is training affected by a workflow diagram?',
        options: ['Training is easier.','Training is harder.','Life is harder.'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'What was the definition of human resources?',
        options: ['Charge of human centric activities.','Preschool activities.','Financial Activities.','Transactions.'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'What was the definition of marketing?',
        options: ['Finances.','All customers.','Customer centric activities.','Advertising only.'],
        answer: 2,
        topic:'Exam 3',
    },
    {
        q:'What was the definition of accounting?',
        options: ['Leads all financial activity.','Handles timesheets only.','Leads customer activity.','Handles the forklift.'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'What was the definition of Production?',
        options: ['Leads work for customers and ads.','Only does sales.','Only sends spam email.','Leads work production and retail.'],
        answer: 3,
        topic:'Exam 3',
    },
    {
        q:'What was the definition of the Research department?',
        options: ['They play COD all day.','They travel all the time.','They send you that email and then call.','Involved with new product design and discoveries.'],
        answer: 3,
        topic:'Exam 3',
    },
    {
        q:'What was the definition of the Research department?',
        options: ['Top down.','Mostly sideways.','Through interpreters.','Bottom up.'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'How does functional view departments share info?',
        options: ['Within each department and then upwards.','By email and pigeon.','Mostly in the bathroom.','Across departments.'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'In functional view how do departments cooperate?',
        options: ['Use only the best departments info.','Info is shared at the managerial level.','Info is shared across departments.','Info becomes scarce.'],
        answer: 1,
        topic:'Exam 3',
    },
    {
        q:'Define top manager.',
        options: ['Executive for long range success.','Executives for bonuses only.','Middle manager looking to backstab.','Supervisor that says smile more.'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'Define middle manager.',
        options: ['Creates short term goals and progress.','Wants long range success','Wants to party and be liked.','Sits all day.'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'Define supervisor.',
        options: ['Monitors all operational matters.','The one that drives a Tesla.','Not the one that drives a Tesla.','They travel all the time'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'Define informational flow level?',
        options: ['How information moves through a system or department.','How email flows through a system.','A level where all info stops.','The thing in the toilet bowl to stop water.'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'What is a publish subscribe IT system?',
        options: ['The flow of info by department.','Notification pings all subscribers for new data.','A newspaper delivery.','Each department has a craft day.'],
        answer: 1,
        topic:'Exam 3',
    },
    {
        q:'What is a push IT system?',
        options: ['A record is created in two departments when sharing data.','A record is sold to spammy email people.','A record is deleted by accident.','A record becomes the best record it could be.'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'What is a pull IT system?',
        options: ['A single record is stored and recalled from a single data point.','A record is created in two departments.','Youre forced to go to an office thing.','A record is moved and then lost.'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'What is choreography IT systems?',
        options: ['Everything is running and sharing info to complete something.','A single point of contact for data.','A range of data.','A record is moved and then lost.'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'What is orchestration IT systems?',
        options: ['A single controller sends info to each directing an action','A universal remote controller.','A pit of electronic equipment.','A single controller only monitors info.'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'What is complex event processing?',
        options: ['Looking for patterns in streams to automatically respond to events.','Looking a single direction to record events.','A record is deleted by accident.','Security looking up a visitor.'],
        answer: 0,
        topic:'Exam 3',
    },

    {
        q:'What is event handling IT systems?',
        options: ['A single controller decides where information goes and responds.','A single controller looks for patterns.','A range of data.','A driver for video screens.'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'What is communication IT systems?',
        options: ['Email.','Pigeon.','Youtube commercials.','That last bit of coffee in the pot.'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'What is a knowledge IT system?',
        options: ['Any info created by humans.','Any info created by computers.','Any info created by Walmart.','All info at the DMV.'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'What is explicit knowledge in a KMS?',
        options: ['Knowledge with documentation.','Knowledge that makes your hair gray.','Knowledge with all opinions.','Absolutely useless knowledge.'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'What is tacit knowledge in a KMS?',
        options: ['Personal experiences and judgement.','All judgements.','Only opinions.','Any info created by humans.'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'What is implicit knowledge in a KMS?',
        options: ['Things that you know without knowing. Like, riding a bike.','Things you think you know.','Other things other people know.','Things that you know with knowing.'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'What is a benefit of a KMS?',
        options: ['Faster resolutions.','Faster computers.','Faster Wifi','Friendlier call center people.'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'Who are the three groups that benefit from a KMS?',
        options: ['Operations. Customer Experience. Employee experience.','Operations. Customer Experience. Employee experience.	Parking.Wifi.Break rooms.','Production.Hold times.Headsets.','Libraries.Streets.Management.'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'What does MIS provide for?',
        options: ['Strategy and management control.','Strategy and building control.','Strategy and long term parking.','Controls and surveillance.'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'What does MIS determine?',
        options: ['The general direction of the company.','The specific direction through modeling.','All models are general.','All statistics are shared by departments.'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'What are the three levels of responsibilities in an organization?',
        options: ['Operational control. Management control. Strategic planning.','Subcompany.Main company. Third party.','SLA. EULA. CER.','Strategy. CE. Bonuses.'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'What is the definition of a knowledge worker?',
        options: ['Those who create and use knowledge to solve problems.','Those who create Art for profit.','Other people doing other things.','Those in charge looking long term. '],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'What are the directions information can flow in an organization?',
        options: ['Downwards, upwards, horizontally, and diagonally.','In, out, up, down.','Left, Right, Left, Right, B, A, Start.','First, second, third fourth.'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'What are the three major steps in information flow?',
        options: ['Collection. Preparation. Input.','Decide.Choose.Do you want whip cream?','Gather.Hunt.Dinner.','Planning. Execution. Monitoring.'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'Why is information flow important?',
        options: ['Sharing between departments reduces miscommunication.','Sharing between departments increases miscommunication.','Departments are run as separate businesses.','There is no sharing in business.'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'What are the three ways information flows in supply chain management?',
        options: ['Material. Information. Financial.','Production. Accounting. Human resources.','Storage. Input. Output.','Supervisor. Middle. Executive.'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'What are the four stages of information processing?',
        options: ['Input. Processing. Storage. Output.','Data. Customer. Manager. KMS.','Production. Operations. Executive. Stakeholder.','Planning. Execution. Monitoring. Production.'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'What are the four stages of data processing?',
        options: ['Collection. Input. Processing. Out.','Planned backup. Patch. Operation. Saving.','Data. Customer breach. Database backup. Cancel cards.'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'What are the four stages of information processing?',
        options: ['Input. Processing. Storage. Output.','Data. Customer. Manager. KMS.','Production. Operations. Executive. Stakeholder.','Planning. Execution. Monitoring. Production.'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'Why is information flow important?',
        options: ['Sharing between departments reduces miscommunication.','Sharing between departments increases miscommunication.','Departments are run as separate businesses.','There is no sharing in business.'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'Who proposed information flow theory?',
        options: ['Paul Lazarsfeld.','Robert Lazarsfeld.','Mike Lazerfield.','Lotte Bailyn'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'What is an opinion leader?',
        options: ['An influencer.','A librarian.','A Protestant.','A liar.'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'Using information flow theory where do people get info from?',
        options: ['Opinion leaders.','Policeman.','Priests.','Customers.'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'Where did they not get their information in information flow theory?',
        options: ['Mass media.','Priests.','Public servants.','Politicians.'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'In information flow theory how many people changed their mind after media consumption?',
        options: ['5%','10%','25%','None'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'What is the Limited Effects paradigm?',
        options: ['Social circles determine choices over media.','Media determines choices over social circles.','Information consumed changes thoughts.','Relationships sway choice.'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'How does the public respond to media messages?',
        options: ['They dont respond until their group responds.','They dont respond until politicians respond.','They respond by party lines.','They allow most things.'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'After TV did the information flow theory change?',
        options: ['No.','Yes.','Maybe.','Sometimes.'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'What is data?',
        options: ['Facts that become useful information.','Opinions that become useful.','Other people thinking about you.','The amount of likes on a post.'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'What is a computer based information system?',
        options: ['A collection that transforms data into useful information.','A partial system used to store information.','A small software company startup.','Cloud computing.'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'What is an office automation system? (OAS)',
        options: ['A process that makes the office more productive.','A process that makes workers more productive.','A management training seminar.','A new type of workout.'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'What is a transaction process system?',
        options: ['Records daily transactions from users.','Records mass transit systems.','Hold music while waiting for an operator.','Controls your bathroom breaks.'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'Name one example of a TPS?',
        options: ['Hotel reservations.','A parking meter.','A beer tap.','A traffic light.'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'What are one of the five categories of functional perspective?',
        options: ['Accounting.','Security.','Maintenance.','Benefits.'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'What are the three organizational categories of information systems?',
        options: ['Operational. Management. Strategic.','Distribution. Logistics. Training.','Accounting.Human resources. Retail.','Payroll. Management. Production.'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'Name one of the three organizational categories in an information system.',
        options: ['Strategic.','Tactical.','Retail.','Maintenance.'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'Which organization category establishes short term goals?',
        options: ['Operational.','Security.','Network Engineering.','Retail.'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'Which organization category establishe long term goals?',
        options: ['Management.','Operational.','Maintenance.','Human resources.'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'Which organization category establishes projections from data models?',
        options: ['Strategic.','Operational.','Management.','Retail.'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'What operation level system handles working hours?',
        options: ['Retail.','Maintenance.','Information Technology.','Payroll.'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'What operation level system handles customer or business to business purchases?',
        options: ['Sales.','Payroll.','Marketing.','Advertising.'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'What operation level system handles amounts and raw products?',
        options: ['Material inventory.','Maintenance.','Information Technology.','Advertising.'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'Are management level systems ______?',
        options: ['Less structured.','More structured.','More disciplined.','Less discipline.'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'Management level systems use __________ to make decisions.',
        options: ['modeling','designs','discipline','vacations'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'Management level systems create theories with _________ questions.',
        options: ['what if','not now','more work','less work'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'Who thinks about where the company will be in five years?',
        options: ['Strategic level managers','Operational managers','Mangement managers','Those one managers.'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'Which management level thinks of long term what if questions?',
        options: ['Senior managers','Supervisors','Steve','Compliance'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'Strategies. Long term what if questions. Five year plans are under what management level?',
        options: ['Strategic.','Operational.','Production.','Middle manager.'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'What other information systems count on TPS systems?',
        options: ['Everything.','DSS','ESS','DBMS'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'What does TPS stand for?',
        options: ['Transaction process system.','Touring Processor Statistics.','Transaction paperless system.','Training pipeline supervisor.'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'What does DSS stand for?',
        options: ['Decision support system.','Durable specific support.','Data strategy system','Data specific systems.'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'What does ESS in data systems stand for?',
        options: ['Executive Support System','Employee Self Service','Electronic Safety Support','Electrical Static System'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'What does DBMS stand for?',
        options: ['Database Management System','Doable Material System','Data Breach Management System','Decision Based Management System'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'Who uses DSS systems?',
        options: ['Managers.','Maintenance.','Supervisors.','Hourly employees.'],
        answer: 0,
        topic:'Exam 3',
    },
    {
            q:'What info makes a DSS system?',
            options: ['External data and models.','Internal data and work hours.','Internal data and research.','External data and TPS.'],
            answer: 0,
            topic:'Exam 3',
        },
        {
            q:'Who uses external data models in a DSS system?',
            options: ['Decision makers.','Supervisors','Information Technology.','Aliens.'],
            answer: 0,
            topic:'Exam 3',
        },
        {
        q:'_______ is used in a DSS system.',
        options: ['Technical data','Worker hours.','Logs.','Research.'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'_______ is used in a DSS system.',
        options: ['Nuance','Inaccuracy','Estimates','Email'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'In a DSS system what are data points?',
        options: ['Everything','Spreadsheets','Email','Customers'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'How does a DSS system get the data?',
        options: ['From user inputs.','From customer input','From employee inputs','From astrology'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'DSS systems use ____ and ___ to produce optimal solutions.',
        options: ['data points and tables','models and statistics','technical data and nuance','customer surveys and strategy'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'You use DSS systems to find _____ solutions from data points and tables.',
        options: ['optimal','most excellent','mediocre','mapping'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'What are the results called when using a DSS system?',
        options: ['Queries','Reports','Data points','Spreadsheets'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'What is a QBE?',
        options: ['Query by example','Query bias end','Quotient based example','Quality by engineer'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'What math operations are used for a query?',
        options: ['greater than less than equals','plus minus equals','function less than equals','multiple parenthesis great than'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'What are DSS systems also called?',
        options: ['Business intelligence systems.','Business information systems','Built Informatic Strategies','Broadcast intelligence systems'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'______   _____ use ESS to make decisions.',
        options: ['Senior managers','Middle managers','No managers','Some managers'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'How accurate can ESS systems implement data points?',
        options: ['Minute by minute operations in some businesses','Daily','Weekly','As needed'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'Does the ESS only use data points?',
        options: ['No, it uses graphs and models to help assist decisions.','Yes, data driven.','Manger dependent.','Business dependent.'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'What uses more analytical models ESS or DSS?',
        options: ['DSS','ESS'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'What is a major source of data for all systems?',
        options: ['TPS','MIS','DSS','ESS'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'Which information system makes reports?',
        options: ['All of them.','None of them.','User defined.','Privileged'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'What comes first decisions or reports?',
        options: ['Decisions','Reports'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'Are reports different than queries?',
        options: ['Yes','No'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'What report lists unusual events?',
        options: ['Exceptions','Management','DSS','TPS'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'What format are DSS reports created in?',
        options: ['There is no format','Spreadsheet','Db file','PPS'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'Name one of the four parts of DSS reports',
        options: ['Decision models','Statistics','Graphs','Spreadsheets'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'Name one of the four parts of DSS reports',
        options: ['Data','external information','filtered information','queries'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'Name one of the four parts of DSS reports',
        options: ['System software','Third party software','Freelance coder','Spreadsheets'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'Name one of the four parts of DSS reports.',
        options: ['User','Spatial models','Linear equations','Administrator'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'Name one of the three decision models for DSS reports',
        options: ['Strategic','Rational','Vroom-Yelton','User'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'Name one of the three decision models for DSS reports',
        options: ['Tactical','User','Rational','Vroom-Yelton'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'Name one of the three decision models for DSS reports',
        options: ['Operational','Vroom-Yelton','User','Intuitive'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'Define the user in a DSS report.',
        options: ['Anyone who makes a decision.','Supervisors','Employees','Contractors'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'Define system software in a DSS report.',
        options: ['Operating system','System software','Firmware','Apps'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'Define data sources in a DSS report.',
        options: ['Internal and external','External only','Internal only','Media only'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'What is a strategic DSS decision model?',
        options: ['Long range planning.','Short range planning.','Tactical takeovers.','Outsourcing.'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'Who uses strategic DSS decision models?',
        options: ['Top level managers.','Supervisors','Production floor.','Forklift drivers.'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'Name one of the three skills data workers have.',
        options: ['Statistics.','Common sense.','Rational.','Delusions.'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'Name one of the three skills data workers have.',
        options: ['Programming.','Blame shifting.','Storytelling','Crypto mining.'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'Name one of the three skills data workers have.',
        options: ['Analysis.','Forklift driving','Rational','English speaker'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'Data workers use ____    programming, and analysis before they make decisions.',
        options: ['knowledge','intuition','coffee','blameshifting'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'Data workers use knowledge, ______ , and analysis before they make decisions.',
        options: ['Programming','storytelling','intuition','thinking'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'Data workers use knowledge, programming, and _____ before they make decisions.',
        options: ['analysis','blameshifting','long rides,','software'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'Name one of the four data workers primary activity',
        options: ['Collect data','Move data','Set privileges','Manage time'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'Name one of the four data workers primary activity',
        options: ['Store data','Destroy data','Set access','Vacation requests'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'Name one of the four data workers primary activity',
        options: ['Manage data','Use a stapler','Email passwords','Set privileges'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'Name one of the four data workers primary activity',
        options: ['Analyze data','Drive forklifts','Set privileges','Manage time'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'Organized data into useful categories is _________.',
        options: ['Structured data','OCD','Bored person','Managed data'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'Data without a format and stored together is ________.',
        options: ['unstructured data','a box of photos','stored data','managed data'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'Code added to data for search engines to understand is _______.',
        options: ['Schema markup','Hashtag','Trending hashtags','LOOKUP command'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'What type of data is social media?',
        options: ['Unstructured data.','Structured data','Managed data','Stored data'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'The __________ is structured when adding something to social media.',
        options: ['post','hashtag','caption','photo'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'The __________ is unstructured when adding something to social media.',
        options: ['content','post','hashtag','blog post'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'Name one of the industries with the lowest population of data workers.',
        options: ['Construction','Hotel management','Labor','Food production'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'Name one of the industries with the lowest population of data workers.',
        options: ['Construction','Hotel management','Labor','Food production'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'Name one of the industries with the lowest population of data workers.',
        options: ['Healthcare','Labor','Plumbing','Assembly'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'If you were in the office you were _____     _____ if you were out of the office you were manual workers.',
        options: ['knowledge workers','office personnel','a big deal','looking around'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'How do you get explicit knowledge in law?',
        options: ['Formal education.','Technical college','Afterschool programs','Breaking the law'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'What type of knowledge is learning on the job?',
        options: ['Tacit','Tactical','Operational','Formal'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'Drucker definition of knowledge worker includes…',
        options: ['Theoretical knowledge','Hunches','Really big library','Large brains'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'What is the Drucker definition of knowledge worker?',
        options: ['Forecast reporting','Operational somethings','Production meetings','Bonuses'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'Drucker definition of knowledge worker includes…',
        options: ['Operational metrics','Hunches','Production meetings','Formal education'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'What percentage of the labor force is knowledge workers?',
        options: ['60%','40%','15%','7%'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'What is the estimated amount of knowledge workers?',
        options: ['100 million','25 million','2 million','50,000'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'The Zand definition of knowledge worker says most work is…',
        options: ['in the head','through programming','through formal education','on the job'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'What year did the knowledge worker outnumber the manual worker?',
        options: ['1956','1965','1932','2010'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'Drucker definition of work is a process that creates a _______.',
        options: ['result','spreadsheet','more work','more problems'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'A physical view of data is using the _____ database.',
        options: ['real','proposed','backup','shared'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'A logical view of data is using the _____ database.',
        options: ['imagined','real','backup','shared'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'A data element is a(n) _______ label of raw data.',
        options: ['organizational','managerial','supervisory','physical'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'What is a data element?',
        options: ['Labeled raw data','Unstructured data','raw data','Sci fi movie'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'What is a smaller physical data element?',
        options: ['A field','A table','A spreadsheet','A sandwich'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'The FIRST NAME field header is an example of?',
        options: ['A data element','Application header','An invitation','A table'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'The Vroom-Yelton decision making model says theres no ideal process for making…',
        options: ['decisions','data','surveys','models'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'A ________ field in a record is a key field.',
        options: ['unique','standard','modern','Microsoft'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'A _________ separates the record from all other records.',
        options: ['unique key','car key','software key','unique data'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'Identify one of the eight types of keys in a DBMS.',
        options: ['Super','Regular','Unleaded','Software'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'Identify one of the eight types of keys in a DBMS.',
        options: ['Primary','Secondary','Tertiary','Frank'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'Identify one of the eight types of keys in a DBMS.',
        options: ['Candidate','Child','Parent','Policy'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'Identify one of the eight types of keys in a DBMS.',
        options: ['Alternate','Backup','Regular','Software'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'Identify one of the eight types of keys in a DBMS.',
        options: ['Foreign','Domestic','Draft','Light'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'Identify one of the eight types of keys in a DBMS.',
        options: ['Compound','Domestic','Backup','Regular'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'Identify one of the eight types of keys in a DBMS.',
        options: ['Composite','Carbon','Backup','Software'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'Identify one of the eight types of keys in a DBMS.',
        options: ['Surrogate','Parent','Light','Normal'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'A ______ key is a group of single or multiple keys in a table',
        options: ['Super','Compound','Composite','Surrogate'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'Can you have multiple keys to identify rows in a table?',
        options: ['Yes','No'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'How many primary keys can a table contain?',
        options: ['1','2','3','4'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'A _____ forecast is an example of real time processing.',
        options: ['weather','farm','freshman student','composite'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'Credit card transactions are an example of _________ processing.',
        options: ['batch','real time','bank','render'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'The Windows registry is an example of a ________ database.',
        options: ['hierarchical','numerical','network','real time'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'A _________ database can have multiple parent and multiple child records.',
        options: ['network','hierarchical','real time','bank'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'A _________ database can have only a single parent and many child records.',
        options: ['hierarchical','network','batch','render'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'A _______ stores small amounts of data with no relation.',
        options: ['DBMS','RDBMS','RSQL','ATM'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'______ is an example of a relational database.',
        options: ['MySQL','DBMS','RSQL','BANK'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'A _____ shape is used to describe a multidimensional database.',
        options: ['cube','pyramid','spare tire','cone'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'Which database model is optimized for data warehouses?',
        options: ['Multidimensional','Relational','RDBMS','Hierarchical'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'How does a multidimensional database work?',
        options: ['Overlaps relational databases','Overlaps network databases','Combines hierarchical dbs','Makes wool hats'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'Do you ask queries or questions to multidimensional databases?',
        options: ['Questions','Queries'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'________ is an example of an object-oriented database.',
        options: ['Javascript','MySQL','Hierarchical','Network'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'_________ stores data as objects.',
        options: ['Object oriented','Network','Hierarchical','Queries'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'What handles larger and more complex data MySQL or OODBMS?',
        options: ['OODBMS','MySQL',],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'What is the primary key called in OODBMS?',
        options: ['OID. Object identifier.','Primary key','Network key','Super key'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'A _______ database holds frequently used and custom information for a user.',
        options: ['personal','custom','network','super'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'What is another name for a personal database?',
        options: ['individual','custom','customer','network'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'Where are personal databases usually stored?',
        options: ['individual computer','public network','cloud drive','super drive'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'A past purchases field would be in a ________ database.',
        options: ['company','public','cloud drive','super'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'A CUSTOMER CONTACT field name would in what database?',
        options: ['Company','Super','Network','Personal'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'Microsoft is an example of a ______ database.',
        options: ['company','public','network','personal'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'A ______ database helps companies make better decisions.',
        options: ['company','public','network','personal'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'Is Microsoft Excel a database?',
        options: ['Yes','No'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'Are some business databases public?',
        options: ['Yes','No'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'Apache is an example of a ______ database.',
        options: ['distributive','relational','public','company'],
        answer: 0,
        topic:'Exam 3',
    },
    {
            q:'Google Spanner is an example of a ______ database',
            options: ['distributive relational','relational','network','company'],
            answer: 0,
            topic:'Exam 3',
        },
        {
        q:'What is a physical example of a distributed database system?',
        options: ['Phone book','Social media followers','Restaurant menu','SSN'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'A collection of information available online is what kind of database?',
        options: ['Commercial Online','Relational','Network','Company'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'What type of database is MySQL?',
        options: ['Open source relational','Commercial relational','Commercial heirarchical','Commercial network'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'What are the two ways to view data?',
        options: ['Physical','Logical'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'Are facts and observations numbers, letters, and symbols?',
        options: ['No','Yes'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'What is the physical view of data?',
        options: ['The format and location','The format only','The location only','What network?'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'What does the logic view of data focus on?',
        options: ['Meaning','Format only','Location','System'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'Name one of the five organization types in logic view.',
        options: ['Character','Name','Location','System'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'Name one of the five organization types in logic view.',
        options: ['Field','Symbol','System','Location'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'Name one of the five organization types in logic view.',
        options: ['Record','Name','Subdomain','Symbol'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'Name one of the five organization types in logic view.',
        options: ['Table','Format','Location','System'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'Name one of the five organization types in logic view.',
        options: ['Database','Symbol','Name','Reference'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'What are the two ways data is processed?',
        options: ['Batch and real-time','Batch and Network time','Real-time and Super time','Queue and real-time'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'_____ processing is collected data that is sent later.',
        options: ['Batch','Real-time','Real batch','Patch'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'______ processing happens immediately when requested.',
        options: ['Real-time','Batch','Network','Packet'],
        answer: 0,
        topic:'Exam 3',
    },
    {
          q:'_____ is a collection of integrated data.',
          options: ['Database','Network','LAN','Processing'],
          answer: 0,
          topic:'Exam 3',
      },
      {
        q:'_____ same info in multiple files.',
        options: ['Data redundancy','Data efficiency','Data reflection','Data magnets'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'______ is the accurate updating of files.',
        options: ['Data integrity','Data respect','Data reflection','Data redundancy'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'Is sharing an advantage to having databases?',
        options: ['Yes','No'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'What improves when departments share a database?',
        options: ['Data redundancy','Data reflection','Data integrity','Data networks'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'What increases when your database has limits to user access?',
        options: ['Security','Data redundancy','Data networks','Networks'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'What increases when your fields have input rules?',
        options: ['Data integrity','Data security','Data networks','Security'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'______ software allows users to make, modify, and access data.',
        options: ['DBMS','Network','Math','Word processor'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'What bridges the logical view and physical view in database software?',
        options: ['DBMS engine','Software drivers','Video card','Word processor'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'What two pieces of info define a datas logical structure?',
        options: ['Schema and structure','Structure and network','Processors speed and Video','Storage and network'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'_____ collection of descriptions of data objects and items.',
        options: ['Data dictionary','Data network','Google translate','Microsoft Clippy'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'______ an analysis tool to view parts of data.',
        options: ['QBE','DND','DSL','DBMS'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'______ an analysis tool to view parts of data.',
        options: ['SQL','ARM','CPU','DBMS'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'What do you use to transform, repair, and investigate data?',
        options: ['DBMS','ARM','EXCEL','CPU'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'What provides tools to create data entries?',
        options: ['Application generation subsystems','ARM','DND','Application general stacks'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'DBMS needs data that is what?',
        options: ['Logically structured','Unstructured data','Raw data','Unshaved data'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'What shaped does a hierarchical database look like?',
        options: ['Upside down tree.','Pineapple','Pie','Cow'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'What database can have a bunch of parents?',
        options: ['Network','Hierarchical','Object Oriented','Personal'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'This database has rows and columns.',
        options: ['Relational','Network','DBMS','Company'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'This database stores data in cubes.',
        options: ['Multidimensional','Network','DBMS','Cow'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'Uses classes, objects and methods.',
        options: ['Object-oriented','Multidimensional','Cow','Personal'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'What is the relationship to nodes in a hiearchical database?',
        options: ['one-to-many','many-to-many','some-to-few','wait-in-line'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'How many parents does a hierarchical database have?',
        options: ['1','2','3','4'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'How many child nodes can a parent node have in a hierarchical database?',
        options: ['Lots','None','1','2'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'Parent node is deleted what happens to the children in a hierarchical database?',
        options: ['All children deleted','All children remain','Good children remain','Bad children deleted'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'How do you avoid losing all the data in a hierarchical database?',
        options: ['Dont delete the parent node,','Delete the parent node','Delete the children nodes','Trim the data moustaches'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'What node arrangement is a network database?',
        options: ['Hierarchical','Network','DVMS','Spatial'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'Children can have _______ parents in a network database?',
        options: ['more than one','only one','three','four'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'A network database is a ______ to ______ relationship.',
        options: ['many-to-many','none-to-many','one-to-many','some-to-none'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'What are the extra connections between children and parents called?',
        options: ['Pointers','Stickers','Labels','Nodes'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'Data stored in tables is called a what in relational databases?',
        options: ['Relation','Pointer','Labels','Field Name'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'How do you link tables in a relational database?',
        options: ['Common data items','Pointers','Unique data items','Field Names'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'What do tables consist of?',
        options: ['Rows and columns','Headers and footers','Formats and cells','Letters and numbers'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'What is a multidimensional database related too?',
        options: ['Company','Object Oriented','Relational','Personal'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'What kind of data is best represented in a multidimensional database?',
        options: ['Complex','Simple','Technical','Math'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'What improves in a multidimensional database over a relational database?',
        options: ['Concept','Ordering','Customer service','Language'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'Which has faster processing a relational or multidimensional database?',
        options: ['Multidimensional ','Relational'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'What is an attribute in an object oriented database?',
        options: ['data fields of an object','data fields in a table','overdue library books','number fields only'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'What are methods in an object oriented database?',
        options: ['instructions for attribute values','instructions for table values','installed queries','concepts'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'Name one of three types of commercial databases.',
        options: ['ProQuest Dialog','Relational','Customer service','Incident'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'Name one of three types of commercial databases.',
        options: ['Dow Jones Factiva','Network','Logical','Hierarchical'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'Name one of three types of commercial databases.',
        options: ['LexisNexis','Relational','Logical','Object Oriented'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'Name one of four types of databases.',
        options: ['Individual','LexisNexus','Logical','Network'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'Name one of four types of databases.',
        options: ['Company','Relational','logical','Partnered'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'Name one of four types of databases.',
        options: ['Distributed','Relational','Logical','Network'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'Name one of four types of databases.',
        options: ['Commercial','NoSQL','Network','Hierarchical'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'_____ is a strategic use for a database.',
        options: ['Data warehouse','Product ordering','Finding relationships','Storing data'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'______ is a strategic use for a database.',
        options: ['Data mining','Harvesting ants','Networking','Storing data'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'Can you use a database as a firewall?',
        options: ['Yes','No'],
        answer: 0,
        topic:'Exam 3',
    },
    {
          q:'Who finds the fastest to classify data in a company?',
          options: ['Database administrators','Stakeholder','Customer','Bosses'],
          answer: 0,
          topic:'Exam 3',
      },
      {
        q:'Who is responsible for database backups?',
        options: ['Database administrators','Stakeholders','Help desk','Customers'],
        answer: 0,
        topic:'Exam 3',
      },
        {
        q:'Who is responsible for database security?',
        options: ['Database administrators','Stakeholders','Help desk','Customers'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'Name one of the six phases of a system life cycle.',
        options: ['Preliminary investigation','Janitorial maintenance','Stakeholder meetings','Customer relations'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'Name one of the six phases of a system life cycle.',
        options: ['Systems analysis','Customer analysis','Stakeholder meetings','Systems integration'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'Name one of the six phases of a system life cycle.',
        options: ['Systems design','Building design','State restrictions','Customer experience'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'Name one of the six phases of a system life cycle.',
        options: ['Systems development','Investigation','Customer design','Build/test'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'Name one of the six phases of a system life cycle.',
        options: ['Systems implementation','Product development','User experience','Password Reset'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'Name one of the six phases of a system life cycle.',
        options: ['Systems maintenance','Building maintenance','User experience','Customer experience'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'________finds the needs for a new information system.',
        options: ['Preliminary investigation','Deep investigation','Adminstrator review','System design'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'After the preliminary investigations all problems are ________.',
        options: ['reported','solved','reset','planned'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'What method is used to identify top level components?',
        options: ['Top down','Bottom up','Sideways','Right'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'What charts show relationships between input and output documents?',
        options: ['Grid','Map','Data','Customer experience'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'What do system flowcharts represent?',
        options: ['Flow of input data','Flow of output data','Processing problems','System research'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'__________ show the data or information flow within an information system.',
        options: ['Data flow diagram','System flow diagram','Network System diagrams','Workflow'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'What is CASE short for?',
        options: ['Computer aided software engineering.','Coke and Soft Earwax','Computer aided strategic engineering','Complex and Static Electricity'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'After analyzing data in a new system what is the report called?',
        options: ['System analysis report','System alma matter report','Strategic analysis report','Standing around report'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'Name one of three tasks for system design.',
        options: ['Define alternatives','Store in the cloud','Outsource','Find weaknesses'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'Name one of three tasks for system design.',
        options: ['Select best system','Workflow diagram','Cloud computing','System analysis report'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'Name one of three tasks for system design.',
        options: ['System design report','System analysis report','Cloud outsourcing','Redundant backups'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'What should you look at first when upgrading a system?',
        options: ['Economics','Technology','Agreements','Revenue'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'When designing a system what users should you exclude?',
        options: ['None','All','Some','Customers'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'Can technology solve everything for a company?',
        options: ['No','Yes','Maybe','Sorta'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'Name one of the three steps of system development.',
        options: ['Acquire software.','Acquire paycheck','Get In N Out','Test software'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'Name one of the three steps of system development.',
        options: ['Acquire hardware.','Acquire backup storage','Test software','Sell old system'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'Name one of the three steps of system development.',
        options: ['Test system','Test software','Test network','Acquire backup storage'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'Name one of two types of system conversions.',
        options: ['Direct','Input','Output','Sofware'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'Name one of two types of system conversions.',
        options: ['Parallel','Software','Redundant','Upgrade'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'______ conversion changes every component in a system',
        options: ['Direct','Direction','Output','Network'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'______conversion adds the new system with the old system',
        options: ['Parallel','Direction','Software','Network'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'______conversion experiments with a new system by department.',
        options: ['Pilot','Software','Network','Independent'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'______conversion new components are added over time.',
        options: ['Phased','Direction','Independent','Network'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'Name one of the two parts of system maintenance.',
        options: ['Periodic evaluation.','Random inspection','Network audit','Software evaluation.'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'______old performance is compared to current performance.',
        options: ['System audit','Pilot audit','Random inspection','Software evaluation'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'______planned inspection of a systems performance.',
        options: ['Periodic evaluation','Random inspection','Pilot audit','Network audit'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'_____ build a model system',
        options: ['Protyping','Logical typing','Networking','Software modeling'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'______shorter development and better quality than models.',
        options: ['Rapid application development','Prototyping','Logical typing','Networking'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'_______ plans and designs new systems.',
        options: ['System analyst','Regular analyst','Therapist','Life coach'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'What is a system?',
        options: ['Collection of activities','Record of activities','Storage of data','Customer transactions'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'________ a list of instructions to complete tasks.',
        options: ['Programming','Goal setting','Life coaching','Therapy'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'What is programming?',
        options: ['A statement.','A joke.','A life lesson.','A question.'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'Can you make your own program to accomplish a task?',
        options: ['Yes','No'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'What kind of procedure is programming?',
        options: ['Problem solving','Problem finding','Strategy','Reaction'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'Name one of the six steps of programming.',
        options: ['Program specification','Program field testing','Software integration','Software modeling'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'Name one of the six steps of programming.',
        options: ['Program design','Program field testing','Problem finding','Software testing'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'Name one of the six steps of programming.',
        options: ['Program code','Program setup','Training','Customer experience'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'Name one of the six steps of programming.',
        options: ['Program test','Software Test','Network Test','Training'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'Name one of the six steps of programming.',
        options: ['Program documentation','Reference material','Training','User passwords'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'Name one of the six steps of programming.',
        options: ['Program maintenance','System maintenance','Upgrades','Driver failure'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'What is another name for program specification?',
        options: ['Program definition','Program documentation','Training','Software upgrades'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'_______ clear statement of the problem to be fixed.',
        options: ['Program objectives','Program definition','Program documentation','Driver failure'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'Who should determine the inputs and outputs of a program?',
        options: ['User','Programmer','Public','Government'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'What is input data?',
        options: ['User sourced data','Workflow diagram','Public data','Driver data'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'What is processing?',
        options: ['Moving input to data','Moving out','Leaving','Moving output to input'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'What is a module?',
        options: ['Processing step','Software step','Network step','Workflow step'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'What is pseudocode?',
        options: ['An outline','A magic spell','A software hack','What you do at Starbucks'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'______ program summary before coding.',
        options: ['Pseudocode','Outsourcing','Processing','Workflow'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'______graphical steps to complete a process.',
        options: ['Workflow','Pseudocode','Google Maps','Selfies'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'_____takes guessing out of programming',
        options: ['Logic structures','Mapping','Selection','Drop down fields'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'______a completed process that can be repeated if everything is the same',
        options: ['Repetition structures','Life','Selection','Pseudocode'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'What is coding?',
        options: ['Writing the program','Writing the pseudocode','Logic structures','Selection'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'A collection of symbols, words, and phrases….',
        options: ['programming language.','pseudocode.','Logic structures.','program objectives.'],
        answer: 0,
        topic:'Exam 3',
    },
    {
        q:'______ tests and eliminates errors.',
        options: ['Debugging','Programming','Workflow','Pseudocode'],
        answer: 0,
        topic:'Exam 3',
    },
  ]
